### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by thomaslule** [thomaslule/a-checkbox-a-day#11]

**Comment by ThomasBracher** [comment]
Steps i see coming:
* deployment test
* unit tests

:memo: can be achieved concurrently

* integration process with travisCI or equivalent
* finally, functionnal tests with selenium (ruby driver is my choice, to decide then)

**Comment by ThomasBracher** [comment]
I've done it the wrong way: deployment test and functional tests are made.
But: 
* i don't think i can start unit tests
* i don't have power to integrate travisCI or an another tool, i would need the administration rights on the repo. Maybe we can move the repo to a shared organisation (still free)

**Comment by thomaslule** [comment]
Annnnnnd we have deployment test, and unit + selenium tests on travis/saucelabs
