### ISSUE TITLE
using REST for CRUD operation

### ISSUE THREAD

**Issue by ThomasBracher** [thomaslule/a-checkbox-a-day#25]
paths of the applications will rapidly be a problem. I propose to stick to the REST when possible:
* POST `/task` to post new task
* GET `/task/{id}` to get a specific task
* DELETE `/task/{id}`
* POST `/task/{id}` to edit task
* GET `/tasks` to get all tasks

**Comment by thomaslule** [comment]
https://github.com/thomaslule/a-checkbox-a-day/pull/36
